### ISSUE TITLE
Make user-agent configurable

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-v2#13]
Requested here: 

https://groups.google.com/forum/#!topic/zotero-dev/2Uw5MzxL2IU

Could go in config/default.json

**Comment by mtrojan-ub** [comment]
As said on zotero-dev, i think it might be useful to be able to override that at every API call. But a config file would be a good start.

**Comment by mvolz** [comment]
The function of the user-agent is to positively identify the client, so I feel like changing it every time is kind of an abuse of spec... :).

**Comment by mtrojan-ub** [comment]
"abuse" is a hard word... it's more like we would like to use sub-user-agents with more detailed information on each specific use case and also specific contact information, e.g.
- ub_tools/ixtheo (see https://ixtheo.de/harvester)
- ub_tools/krimdok (see https://krimdok.uni-tuebingen.de/harvester)

This way you can see it's the same user-agent (ub_tools)
(URLs not working yet)

Because we might get to the point when multiple hundred pages will be harvested per user agent every night (current plan is up to a total of 1400 journals)... So our goal is to give as detailed information as we can to prevent people from sending questions and/or locking us out

**Comment by dstillman** [comment]
I've made the user agent configurable globally. I don't see us making it configurable per-request, but that's something you could modify for your needs. (Right now it'd be a little tricky, but https://github.com/zotero/translation-server-v2/issues/16 should make it easier.)
